## Pandas
---
##### Series 1차원
##### DataFrame 2차원

#### Series

In [3]:
import pandas as pd
import numpy as np

s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(type(s))
print(s.index)

<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=9, step=1)


In [4]:
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64


In [5]:
s.index = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']
print(s)

A    1
B    2
C    3
D    4
E    5
F    6
G    7
H    8
I    9
dtype: int64


In [6]:
s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9], index = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'])
print(s)

A    1
B    2
C    3
D    4
E    5
F    6
G    7
H    8
I    9
dtype: int64


In [7]:
print(s.index)
print(s.values)
print(s[0])
print(s['A'])
print(s.A)

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'], dtype='object')
[1 2 3 4 5 6 7 8 9]
1
1
1


C:\Users\baka2\AppData\Local\Temp\ipykernel_164\1109782676.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [8]:
print(s[:5])
print(s['A':'E'])

A    1
B    2
C    3
D    4
E    5
dtype: int64
A    1
B    2
C    3
D    4
E    5
dtype: int64


##### Dictionary (Map, JSON) > Serise

In [10]:
d = {'A':10, 'D':20, 'F':30, 'H':40}
print(type(d))
for key, value in d.items() :
    print(key, ":", value)
print(d['A'])

<class 'dict'>
A : 10
D : 20
F : 30
H : 40
10


In [11]:
#print(d.A)
#print(d[0:3])
#print(d['A':'F'])

In [12]:
s = pd.Series(d)
print(s.index)
print(s.values)
print(s['A'])
print(s.A)
print(s[0:3])
print(s['A':'F'])

Index(['A', 'D', 'F', 'H'], dtype='object')
[10 20 30 40]
10
10
A    10
D    20
F    30
dtype: int64
A    10
D    20
F    30
dtype: int64


#### DataFrame

##### Dictionary > DataFrame

In [15]:
d = {
    'name' : ['kim', 'lee', 'park', 'jung'],
    'age' : [25, 30, 35, 20],
    'tel' : ['1111-1111', '2222-2222', '3333-3333', '4444-4444']
}
print(type(d))

<class 'dict'>


In [16]:
df = pd.DataFrame(d)
print(df)
print(df.columns)
print(df.values)

   name  age        tel
0   kim   25  1111-1111
1   lee   30  2222-2222
2  park   35  3333-3333
3  jung   20  4444-4444
Index(['name', 'age', 'tel'], dtype='object')
[['kim' 25 '1111-1111']
 ['lee' 30 '2222-2222']
 ['park' 35 '3333-3333']
 ['jung' 20 '4444-4444']]


In [17]:
df.index.name = 'Num'
df.columns.name = 'User'
print(df)
print(df.columns)
print(df.values)

User  name  age        tel
Num                       
0      kim   25  1111-1111
1      lee   30  2222-2222
2     park   35  3333-3333
3     jung   20  4444-4444
Index(['name', 'age', 'tel'], dtype='object', name='User')
[['kim' 25 '1111-1111']
 ['lee' 30 '2222-2222']
 ['park' 35 '3333-3333']
 ['jung' 20 '4444-4444']]


##### NumPy > DataFrame

In [19]:
n = np.array(
    [['kim', 25, '1111-1111'],
     ['lee', 30, '2222-2222'],
     ['park', 35, '3333-3333'],
     ['jung', 20, np.nan]]
)
print(type(n))

<class 'numpy.ndarray'>


In [20]:
df.columns = ['name', 'age', 'tel']
df.index = ['A', 'B', 'C', 'D']

In [21]:
print(df)
print(df.index)
print(df.columns)

   name  age        tel
A   kim   25  1111-1111
B   lee   30  2222-2222
C  park   35  3333-3333
D  jung   20  4444-4444
Index(['A', 'B', 'C', 'D'], dtype='object')
Index(['name', 'age', 'tel'], dtype='object')


In [22]:
df = pd.DataFrame(n, columns = ['name', 'age', 'tel'], index = ['A', 'B', 'C', 'D'])
print(df)

   name age        tel
A   kim  25  1111-1111
B   lee  30  2222-2222
C  park  35  3333-3333
D  jung  20        nan


In [23]:
print(df.describe())

       name age        tel
count     4   4          4
unique    4   4          4
top     kim  25  1111-1111
freq      1   1          1


In [24]:
print(df['name'])
print(df[['name','tel']])
#print(df['name'][2])
print(df['name']['C'])
print(df['name'].C)
print(df['name']['B':'D'])

A     kim
B     lee
C    park
D    jung
Name: name, dtype: object
   name        tel
A   kim  1111-1111
B   lee  2222-2222
C  park  3333-3333
D  jung        nan
park
park
B     lee
C    park
D    jung
Name: name, dtype: object


In [25]:
print(df.name, df.age)

A     kim
B     lee
C    park
D    jung
Name: name, dtype: object A    25
B    30
C    35
D    20
Name: age, dtype: object


In [26]:
print(df.name.D)

jung


In [27]:
print(df[:][:])
print(df[:2][:1])
print(df[['name', 'tel']])
#print(df[[0, 2]]) #에러 컬럼명이 있는 경우에는 숫자 사용 금지
#print(df[0][0]) #에러

   name age        tel
A   kim  25  1111-1111
B   lee  30  2222-2222
C  park  35  3333-3333
D  jung  20        nan
  name age        tel
A  kim  25  1111-1111
   name        tel
A   kim  1111-1111
B   lee  2222-2222
C  park  3333-3333
D  jung        nan


In [28]:
df['address'] = ['서울', '수원', '인천', '안산']
df['adult'] = df['age'].astype(np.int64) > 30
#df['age']['A'] = 40

del(df['adult'])
print(df)

   name age        tel address
A   kim  25  1111-1111      서울
B   lee  30  2222-2222      수원
C  park  35  3333-3333      인천
D  jung  20        nan      안산


##### Series 정렬

In [30]:
s = pd.Series( [10, 40, 50, 20, 70,60], index = ['a', 'd', 'f', 'g', 'b', 'c'])
s = s.sort_index(ascending = False)
s = s.sort_values(ascending = False)
print(s)

b    70
c    60
f    50
d    40
g    20
a    10
dtype: int64


##### DataFrame 정렬

In [32]:
df = pd.DataFrame([[4, 5, 40, 100],
                   [300, 10, 200, 100],
                   [20, 400, 4, 2]], index = ['c', 'a', 'b'], columns = ['D', 'C', 'A', 'B'])
print(df)

     D    C    A    B
c    4    5   40  100
a  300   10  200  100
b   20  400    4    2


In [33]:
df = df.sort_index() #index
df = df.sort_index(axis=0, ascending = False)
df = df.sort_index(axis=1, ascending = False) #column

df = df.sort_values(by = 'A', ascending = False) #행끼리
df = df.sort_values(by =['A', 'B'])

df = df.sort_values(by = 'b', axis = 1) #열끼리

print(df)

     B    A    D    C
b    2    4   20  400
c  100   40    4    5
a  100  200  300   10


##### 슬라이싱

In [35]:
#.iloc 정수 인덱스
#.loc 라벨 인덱스
#.ix deprecated > 옛날의 방식이기 때문에 사용 추천 안함

In [36]:
#list
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9] ]
print(m)
print(m[2][2])
print(m[:][:])
print(m[:2][:2])
#print(m[:2, :2]) #에러

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6]]


In [37]:
#Numpy
n = np.array(m)
print(n)
print(n[2][2])
print(n[:][:])
print(n[:2][:2])
print(n[:2, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [38]:
#Pandas
df = pd.DataFrame(n)
print(df)
print(df[2][2])
print(df[:][:])
print(df[:2][:2])
#print(df[:2, :2]) #에러

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
9
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
   0  1  2
0  1  2  3
1  4  5  6


In [39]:
#iloc
df = pd.DataFrame(np.arange(1, 21).reshape(5, 4), columns = ['A', 'B', 'C', 'D'])
print(df)
#print(df[2][2]) #에러
print(df['C'][2])
print(df[['A','D']])
#print(df['A' : 'C']) #에러
#print(df[['A' : 'C']]) #에러

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
11
    A   D
0   1   4
1   5   8
2   9  12
3  13  16
4  17  20


In [40]:
print(df.iloc[2][2])
print(df.iloc[2, 2])
#print(df.iloc[2, 'C']) #에러

11
11


C:\Users\baka2\AppData\Local\Temp\ipykernel_164\3385501839.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[2][2])


In [41]:
print(df.iloc[:2, :2])
print(df.iloc[:3:2, :3:2])
print(df.iloc[:2, :-1])
print(df.iloc[::-1, ::-1])

   A  B
0  1  2
1  5  6
   A   C
0  1   3
2  9  11
   A  B  C
0  1  2  3
1  5  6  7
    D   C   B   A
4  20  19  18  17
3  16  15  14  13
2  12  11  10   9
1   8   7   6   5
0   4   3   2   1


In [42]:
#loc
print(df)
#print(df.loc[2, 2]) #에러
print(df.loc[2, 'C'])
#print(df.loc[:2, :2]) #에러
print(df.loc[:2, :'C'])
print(df.loc[:2])
print(df.loc[1:3, 'B':'D'])
print(df.loc[:, 'C'])
print(df.loc[:, ['B','D']])
#print(df.loc[['B','D']])

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
11
   A   B   C
0  1   2   3
1  5   6   7
2  9  10  11
   A   B   C   D
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12
    B   C   D
1   6   7   8
2  10  11  12
3  14  15  16
0     3
1     7
2    11
3    15
4    19
Name: C, dtype: int32
    B   D
0   2   4
1   6   8
2  10  12
3  14  16
4  18  20


In [43]:
df = pd.DataFrame(np.arange(1, 21).reshape(5, 4), columns = ['A', 'B', 'C', 'D'])
df['E'] = [31, 32, 33, 34, 35]
#df[5][:] = [90, 91, 92, 93, 94] #에러
#df.iloc[:, 5] = [40, 41, 42, 43, 44] #에러
#df.iloc[5,:] = [90, 91, 92, 93, 94] #에러
df.loc[5] = [90, 91, 92, 93, 94]
df.loc[:, 'F'] = [40, 41, 42, 43, 44, 45]

df.loc[0, 'A'] = 99
df.loc[1, 'A' : 'C'] = [100, 101, 102]
df.loc[3, ['A', 'C', 'E']] = [200, 201, 202]

print(df)

     A    B    C   D    E   F
0   99    2    3   4   31  40
1  100  101  102   8   32  41
2    9   10   11  12   33  42
3  200   14  201  16  202  43
4   17   18   19  20   35  44
5   90   91   92  93   94  45


In [44]:
del(df['E'])

print(df)

     A    B    C   D   F
0   99    2    3   4  40
1  100  101  102   8  41
2    9   10   11  12  42
3  200   14  201  16  43
4   17   18   19  20  44
5   90   91   92  93  45


In [45]:
#df.drop('F') #에러
print(df.drop('F', axis = 1))

print(df)

     A    B    C   D
0   99    2    3   4
1  100  101  102   8
2    9   10   11  12
3  200   14  201  16
4   17   18   19  20
5   90   91   92  93
     A    B    C   D   F
0   99    2    3   4  40
1  100  101  102   8  41
2    9   10   11  12  42
3  200   14  201  16  43
4   17   18   19  20  44
5   90   91   92  93  45


In [46]:
df = df.drop('F', axis = 1)

print(df)

     A    B    C   D
0   99    2    3   4
1  100  101  102   8
2    9   10   11  12
3  200   14  201  16
4   17   18   19  20
5   90   91   92  93


In [47]:
df = df.drop(5)

print(df)

     A    B    C   D
0   99    2    3   4
1  100  101  102   8
2    9   10   11  12
3  200   14  201  16
4   17   18   19  20


##### Boolean Indexing

In [49]:
df = pd.DataFrame(
    [['kim', 25, '1111-1111'],
     ['lee', 30, '2222-2222'],
     ['park', 35, '3333-3333'],
     ['jung', 20, '4444-4444'],
     ['hong', 40, '5555-5555']], columns = ['name', 'age', 'tel']
)

print(df)
print(df.loc[3, 'name'])
print(df.loc[df['age'] > 30, ['name', 'age']])
print(df.loc[df['name'] == 'kim', :])

   name  age        tel
0   kim   25  1111-1111
1   lee   30  2222-2222
2  park   35  3333-3333
3  jung   20  4444-4444
4  hong   40  5555-5555
jung
   name  age
2  park   35
4  hong   40
  name  age        tel
0  kim   25  1111-1111


In [50]:
print(df.loc[(df['age'] > 20) & (df['age'] < 40), 'name' : 'age'])
print(df.loc[[], "name"])
print(df.loc[[True, True, False, False, False], "name"])

   name  age
0   kim   25
1   lee   30
2  park   35
Series([], Name: name, dtype: object)
0    kim
1    lee
Name: name, dtype: object


##### 결측값 대체

In [52]:
df['address'] = ['서울', np.nan, np.nan, '수원', np.nan]

print(df.loc[df['address'] == np.nan, 'address'])
print(df.loc[df['address'] == None, 'address'])
print(df.loc[df['address'].isnull(), 'address'])

df.loc[df['address'].isnull(), 'address'] = '서울'

df.loc[::2, 'address'] = ''
df.loc[df['address'] == '', 'address'] = '서울

print(df)

SyntaxError: unterminated string literal (detected at line 10) (3447199069.py, line 10)

##### 결측값 제거

In [59]:
# df.loc[::2, 'tel'] = np.nan
# df.loc[5, :] = [np.nan, np.nan, np.nan, np.nan]

# #df.dropna(how = 'all', inplace = True)
# #df.dropna(how = 'any', inplace = True)

# print(df)

In [61]:
df = pd.DataFrame(
    [['kim', 25, '1111-1111', '서울'],
     ['lee', 30, '2222-2222',np.nan],
     ['park', 35, '3333-3333', '수원'],
     ['jung', 20, '4444-4444', np.nan],
     ['hong', 40, '5555-5555', np.nan]], columns = ['name', 'age', 'tel', 'address']
)

df['income'] = [300, np.nan, 400, 500, np.nan, 300]
print(df)

ValueError: Length of values (6) does not match length of index (5)