## Numpy
---
##### Numerical Python  
##### 고성능 수치 계산을 위한 라이브러리  
##### 벡터(1차원, 한 줄로 나열된)나 행렬(2차원, 3차원) 연산에 편리한 기능 제공  
##### 모든 원소는 같은 자료형만 가능  

In [22]:
import numpy as np

b = [-1, 2, 5, -3, 0, 7, -9, 7, -4, -7]
print(np.median(b)) #전체 데이터 중간 값을 알려주는 함수

-0.5


#### 2차원 배열

In [4]:
c = [[1, 2, 3], [4, 5, 6]]
print(type(c))
c = np.array(c)
print(type(c))

<class 'list'>
<class 'numpy.ndarray'>


In [26]:
print(c) #2행 3열

[[1 2 3]
 [4 5 6]]


In [28]:
print(np.sum(c))

21


In [42]:
print(np.sum(c, axis = 0)) #0은 행끼리 계산을 의미, 이번 계산은 1행끼리 더하기, 2행끼리 더하기, 3행끼리 더하기를 의미

[5 7 9]


In [40]:
print(np.sum(c, axis = 1)) #1은 열끼리 계산을 의미, 이번 계산은 1열끼리 더하기, 2열끼리 더하기를 의미

[ 6 15]


In [38]:
print(np.mean(c, axis = 0)) #0은 행끼리 계산을 의미, 이번 계산은 1행끼리 평균, 2행끼리 평균, 3행끼리 평균을 의미

[2.5 3.5 4.5]


In [44]:
print(np.mean(c, axis = 1)) #1은 열끼리 계산을 의미, 이번 계산은 1열끼리 평균, 2열끼리 평균을 의미

[2. 5.]


In [48]:
print(np.median(c,axis = 0))

[2.5 3.5 4.5]


In [50]:
print(np.median(c,axis = 1))

[2. 5.]


In [52]:
print(np.max(c,axis = 0))

[4 5 6]


In [54]:
print(np.max(c,axis = 1))

[3 6]


In [56]:
print(np.min(c,axis = 0))

[1 2 3]


In [58]:
print(np.min(c,axis = 1))

[1 4]


In [62]:
print(np.std(c)) #표준편차

1.707825127659933


In [64]:
print(np.var(c)) #분산

2.9166666666666665


##### element wise

In [77]:
d = [10, 20, 30, 40, 50]
# print(d+2) #error
d = np.array(d) #리스트로는 안되지만 넘파이로는 각각에 데이터에 동일한 계산을 하는 식 가능
print(d+2)

[12 22 32 42 52]


In [83]:
e = np.array([1, 2, 3, 4, 5])
print(d + e)

[11 22 33 44 55]


In [87]:
print(d ** 2) #제곱

[ 100  400  900 1600 2500]


In [89]:
print(d * np.sin(d))

[ -5.44021111  18.25890501 -29.64094872  29.80452642 -13.11874269]


In [93]:
print(d > 35) #비교연산자 논리값으로 도출

[False False False  True  True]


In [101]:
print(np.add(d, e))
print(np.subtract(d, e))
print(np.multiply(d, e))
print(np.divide(d, e))

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [103]:
f = np.array([[0, 1], [1, 1]])
g = np.array([[2, 0], [3, 4]])

In [105]:
print(f * g)

[[0 0]
 [3 4]]


In [109]:
print(f @ g) #행렬곱

[[3 4]
 [5 4]]


In [117]:
print(np.dot(f, g)) #행렬곱
print(f.dot(g))

[[3 4]
 [5 4]]
[[3 4]
 [5 4]]


In [119]:
h = np.zeros(10)
print(h)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [121]:
i = np.zeros((5, 5))
print(i)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [123]:
j = np.ones(10)
print(j)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [125]:
k = np.ones((5, 5))
print(k)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#np.random.random   0~1 사이의 난수 발생
#np.random.randint   균일 분포의 정수 난수 발생
#np.random.rand   0~1 사이의 균일 분포 난수 matrix array 생성
#np.random.randn   가우시안 표준 정규 분포 난수 matrix array 생성
#np.random.nomral   평균, 표준편차 sample 개수

In [128]:
print(np.random.random(10))

[0.43704485 0.98159624 0.72588743 0.94346764 0.94722469 0.61046875
 0.37884783 0.15851114 0.96081086 0.96514329]


In [136]:
l = np.random.random(10) * 100
print(type(l))
print(l)

<class 'numpy.ndarray'>
[60.07920458 16.89202205 85.28834724 28.46657947 39.72635794 69.94285667
 52.19294904 22.84894641 32.72969374 77.47380093]


In [146]:
l = np.random.random(10) * 100
l = [int(i) for i in l]
print(type(l))
print(l)

<class 'list'>
[29, 62, 93, 59, 45, 29, 48, 64, 65, 30]


In [150]:
print(np.random.randint(10, 20))

18


In [152]:
print(np.random.rand(5, 2))

[[0.53344187 0.51576221]
 [0.73589696 0.90306063]
 [0.6964139  0.53981336]
 [0.68111909 0.6683952 ]
 [0.82311713 0.52654704]]


##### 슬라이싱 (리스트 슬라이싱, 넘파이 슬라이싱, 판다스 슬라이싱)

In [180]:
# 1차원 데이터
m = [i for i in range(10, 20)]
print(m[0:5]) # [시작 : 끝-1 : 간격]
print(m[0:5:2])
print(m[:])
print(m[5:])
print(m[:-1]) #가장 뒤 데이터 하나 빼기
print(m[::-1]) # 데이터 거꾸로 출력하기

[10, 11, 12, 13, 14]
[10, 12, 14]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[15, 16, 17, 18, 19]
[10, 11, 12, 13, 14, 15, 16, 17, 18]
[19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


In [190]:
#nparray
w = [np.arange(10, 20)]
print(w[0:5])
print(w[0:5:2])
print(w[:-2])

[array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]
[array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]
[]


In [254]:
r = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
print(r[2][2])
print(r[:][:])
print(r[2][:])
print(r[1][:2])
print(r[:2][:1]) #2차원의 결과값 [[1, 2, 3, 4, 5]]
#print(r[:, :]) #리스트에서는 불가능

13
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[11, 12, 13, 14, 15]
[6, 7]
[[1, 2, 3, 4, 5]]


In [252]:
s = np.arange(1, 16).reshape(3, 5)
print(s)
print(s[2][2])
print(s[:][:])
print(s[2][:])
print(s[:2][:1]) # 2차원의 결과값 [[1 2 3 4 5]]

print(s[:2, :2]) #넘파이에서는 가능
print(s[:, :])
print(s[:-1, :-1])
print(s[2, 2])
print(s[::-1, ::-1]) #행도 거꾸로, 열도 거꾸로

print(s[[0,2]])
print(s[:, [1, 3, 4]])
print(s[[0, 2], [3, 4]]) #0행 3열, 2행 4열 데이터

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
13
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
[[1 2 3 4 5]]
[[1 2]
 [6 7]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[1 2 3 4]
 [6 7 8 9]]
13
[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[ 2  4  5]
 [ 7  9 10]
 [12 14 15]]
[ 4 15]


In [258]:
# 전치 행렬
print(s) #3행 5열
print(s.T) #5행 3열

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


#### 결합 / 분리

In [261]:
a = [1, 2, 3]
b = [4, 5, 6]
for ab in zip(a, b):
    print(ab)

(1, 4)
(2, 5)
(3, 6)


In [263]:
print(list(zip(a, b)))

[(1, 4), (2, 5), (3, 6)]


In [283]:
print(a + b)
print(a * 2)
print(a + 2)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [265]:
c = np.random.rand(2, 2)
print(c)

[[0.48032775 0.74115005]
 [0.55030428 0.13643309]]


In [269]:
c = np.floor(np.random.rand(2, 2) * 100)
print(c)

[[43. 76.]
 [43. 61.]]


In [285]:
d = np.floor(np.random.rand(2, 2) * 100)
print(d)
print(np.hstack((c, d)))
print(np.vstack((c, d)))

[[11. 83.]
 [29. 74.]]
[[43. 76. 11. 83.]
 [43. 61. 29. 74.]]
[[43. 76.]
 [43. 61.]
 [11. 83.]
 [29. 74.]]


In [287]:
print(c + d)
print(c * 2)
print(c + 2)

[[ 54. 159.]
 [ 72. 135.]]
[[ 86. 152.]
 [ 86. 122.]]
[[45. 78.]
 [45. 63.]]


#### 분리

In [293]:
e = np.floor(np.random.rand(2, 15) *100)
print(e)

[[41. 63. 48. 89. 84. 56. 84. 49. 37. 49.  0. 25. 28. 35. 64.]
 [79.  7. 24. 52. 98. 58. 35. 30. 91. 37. 72. 84. 63. 63. 61.]]


In [295]:
print(np.hsplit(e, 3)) #균등하게 3개로 자르는 형태

[array([[41., 63., 48., 89., 84.],
       [79.,  7., 24., 52., 98.]]), array([[56., 84., 49., 37., 49.],
       [58., 35., 30., 91., 37.]]), array([[ 0., 25., 28., 35., 64.],
       [72., 84., 63., 63., 61.]])]


In [297]:
for arr in np.hsplit(e, 3):
    print(arr)

[[41. 63. 48. 89. 84.]
 [79.  7. 24. 52. 98.]]
[[56. 84. 49. 37. 49.]
 [58. 35. 30. 91. 37.]]
[[ 0. 25. 28. 35. 64.]
 [72. 84. 63. 63. 61.]]


In [301]:
for arr in np.hsplit(e, (3, 7,12)): #[0:3] [3:7] [7:12] [12:]
    print(arr)

[[41. 63. 48.]
 [79.  7. 24.]]
[[89. 84. 56. 84.]
 [52. 98. 58. 35.]]
[[49. 37. 49.  0. 25.]
 [30. 91. 37. 72. 84.]]
[[28. 35. 64.]
 [63. 63. 61.]]


In [313]:
f = np.array([1, 2, 3, 4, 5])
g = np.array(['A', 'B', 'C', 'D', 'E'])
h = np.array([True, True, False, False, True])

# 삼항연산      조건 ? 참 : 거짓
#              참 if 조건 else 거짓
print([x if z else y for x, y, z in zip(f, g, h)])


[1, 2, 'C', 'D', 5]


In [319]:
print(np.where(h, f, g))
print(np.where(f < 3, '작다', '크다'))
print(np.where(h, '참', '거짓'))

['1' '2' 'C' 'D' '5']
['작다' '작다' '크다' '크다' '크다']
['참' '참' '거짓' '거짓' '참']


#### 파일 만들기

In [326]:
i = np.arange(10)
np.save('i.npy', i)

In [328]:
ii = np.load('i.npy')
print(ii)

[0 1 2 3 4 5 6 7 8 9]


In [337]:
j = np.arange(10)
k = np.arange(20)
np.savez('jk.npz', x = j, y = k)
jk = np.load('jk.npz')
print(type(jk))
print(jk['x'])
print(jk['y'])

<class 'numpy.lib.npyio.NpzFile'>
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
