## Numpy
---
##### Numerical Python  
##### 고성능 수치 계산을 위한 라이브러리  
##### 벡터(1차원, 한 줄로 나열된)나 행렬(2차원, 3차원) 연산에 편리한 기능 제공  
##### 모든 원소는 같은 자료형만 가능  

In [17]:
import numpy as np
a = np.arange(15) #0부터 14까지
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [19]:
a = a.reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
a = a.reshape(3,6) #데이터가 18개 있어야 해
print(a)

ValueError: cannot reshape array of size 15 into shape (3,6)

In [31]:
a = a.reshape(3,5)
print(type(a))

<class 'numpy.ndarray'>


In [33]:
a = a.reshape(3,5)
print(a.shape)

(3, 5)


In [37]:
a = a.reshape(3,5)
print(a.dtype)

int32


In [39]:
a = a.reshape(3,5)
print(a.ndim)

2


In [43]:
# print(dir(np))

In [45]:
a = a.reshape(3,5)
print(a.size)

15


In [179]:
#C=행부터 할당(기본값), F=열부터 할당
a = np.arange(15)
a = a.reshape(3, 5, order='F')
print(a)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [67]:
b = np.array([-1, 2, 5, 13, 0, 7, 19, 7, -4, -7]) # List
#데이터를 섞어보기/리스트를 가지고 넘파이 객체를 만든 것, 리스트와 넘파이는 호환이 가능하다라고 이해  
print(b)

[-1  2  5 13  0  7 19  7 -4 -7]


In [69]:
b = [-1, 2, 5, 13, 0, 7, 19, 7, -4, -7]
print(type(b))

<class 'list'>


In [71]:
b = np.array([-1, 2, 5, 13, 0, 7, 19, 7, -4, -7])
print(type(b))

<class 'numpy.ndarray'>


In [73]:
t = (10, 20, 30, 40, 50) # Tuple
print(type(t))

<class 'tuple'>


In [75]:
t = np.array(t)
print(type(t))

<class 'numpy.ndarray'>


In [79]:
s = {10, 20, 30, 40, 50} # Set
print(type(s))

<class 'set'>


In [81]:
s = np.array(s)
print(type(s))

<class 'numpy.ndarray'>


In [115]:
b = np.array([-1, 2, 5, -3, 0, 7, -9, 7, -4, -7])
print(type(b))
print(b.shape)
print(b.ndim)
print(b.dtype)
print(b)

<class 'numpy.ndarray'>
(10,)
1
int32
[-1  2  5 -3  0  7 -9  7 -4 -7]


In [117]:
# print(help(np))

In [183]:
print(np.abs(b)) #절대값을 구하는 함수

[1 2 5 3 0 7 9 7 4 7]


In [121]:
print(np.sqrt(b)) #(양수는 계산하지만 음수는 nan 계산하지 못한다) 제곱근을 구하는 함수

[       nan 1.41421356 2.23606798        nan 0.         2.64575131
        nan 2.64575131        nan        nan]


C:\Users\baka2\AppData\Local\Temp\ipykernel_18804\3800773638.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(b)) #(양수는 계산하지만 음수는 nan 계산하지 못한다) 제곱근을 구하는 함수


In [123]:
print(np.sqrt(np.abs(b))) #절대값으로 구한 넘파이 데이터를, 제곱근을 구한 넘파이 데이터를, 프린트

[1.         1.41421356 2.23606798 1.73205081 0.         2.64575131
 3.         2.64575131 2.         2.64575131]


In [185]:
print(np.square(b)) #제곱을 구하는 함수

[ 1  4 25  9  0 49 81 49 16 49]


In [187]:
print(np.isnan(b)) #nan의 여부를 물어보는 함수 (nan일 때 true, nan 아닐 때 false)

[False False False False False False False False False False]


In [131]:
b = np.array([-1, 2, 5, -3, 0, 7, -9, 7, -4, np.nan])
print(np.isnan(b))

[False False False False False False False False False  True]


In [189]:
b = np.array([-1, 2, 5, -3, 0, 7, -9, 7, -4, -7])
print(np.sum(b)) #합계를 구하는 함수

-3


In [191]:
print(np.mean(b)) #평균을 구하는 함수

-0.3


In [153]:
print(np.max(b)) #전체 데이터 중 최대값을 알려주는 함수

7


In [155]:
print(np.min(b)) #전체 데이터 중 최소값을 알려주는 함수

-9


In [161]:
print(np.argmax(b)) #가장 큰 값의 위치(인덱스)를 알려주는 함수, 0에서부터 시작

5


In [165]:
print(np.argmin(b)) #가장 작은 값의 위치(인덱스)를 알려주는 함수, 0에서부터 시작

6


In [171]:
print(np.sort(b)) #오름차순으로 정렬해주는 함수

[-9 -7 -4 -3 -1  0  2  5  7  7]


In [173]:
print(np.sort(b)[::-1]) #내림차순으로 정렬해주는 함수 (오름차순으로 정렬한 뒤 거꾸로 정렬하기)
# [start : end : step] [시작 : 끝 : 간격] -1은 거꾸로

[ 7  7  5  2  0 -1 -3 -4 -7 -9]


In [177]:
print(np.median(b)) #전체 데이터 중중간 값을 알려주는 함수

-0.5
